import csv
from pathlib import Path

from repair_csv_terms import HEADER, make_initials, make_pinyin


ROOT = Path(__file__).resolve().parent.parent
WORDS_DIR = ROOT / "words"


def rows(items):
    return [(cn, difficulty, en) for cn, en, difficulty in items]


PHYSICS_MECHANICS = rows([
    ("质点", "particle", 1),
    ("参考系", "reference_frame", 2),
    ("坐标系", "coordinate_system", 2),
    ("时刻", "instant", 1),
    ("时间间隔", "time_interval", 2),
    ("位置", "position", 1),
    ("位移", "displacement", 1),
    ("路程", "distance_traveled", 1),
    ("速度", "velocity", 1),
    ("平均速度", "average_velocity", 2),
    ("瞬时速度", "instantaneous_velocity", 2),
    ("速率", "speed", 1),
    ("平均速率", "average_speed", 2),
    ("加速度", "acceleration", 1),
    ("匀速直线运动", "uniform_rectilinear_motion", 2),
    ("变速直线运动", "nonuniform_rectilinear_motion", 2),
    ("匀变速直线运动", "uniformly_accelerated_rectilinear_motion", 2),
    ("自由落体运动", "free_fall_motion", 2),
    ("竖直上抛运动", "vertical_upward_throwing_motion", 3),
    ("运动图像", "motion_graph", 2),
    ("位移时间图像", "displacement_time_graph", 2),
    ("速度时间图像", "velocity_time_graph", 2),
    ("斜率", "slope", 2),
    ("面积", "area", 1),
    ("相互作用", "interaction", 2),
    ("力", "force", 1),
    ("重力", "gravity", 1),
    ("弹力", "elastic_force", 1),
    ("摩擦力", "friction_force", 1),
    ("静摩擦力", "static_friction_force", 2),
    ("滑动摩擦力", "kinetic_friction_force", 2),
    ("支持力", "normal_force", 2),
    ("压力", "pressure_force", 1),
    ("拉力", "tension_force", 1),
    ("合力", "resultant_force", 2),
    ("分力", "component_force", 2),
    ("力的合成", "composition_of_forces", 2),
    ("力的分解", "resolution_of_forces", 2),
    ("平行四边形定则", "parallelogram_rule", 3),
    ("牛顿第一定律", "newtons_first_law", 2),
    ("惯性", "inertia", 1),
    ("质量", "mass", 1),
    ("牛顿第二定律", "newtons_second_law", 2),
    ("牛顿第三定律", "newtons_third_law", 2),
    ("作用力", "action_force", 2),
    ("反作用力", "reaction_force", 2),
    ("超重", "overweight", 2),
    ("失重", "weightlessness", 2),
    ("平衡状态", "equilibrium_state", 2),
    ("共点力平衡", "equilibrium_of_concurrent_forces", 3),
    ("曲线运动", "curvilinear_motion", 2),
    ("运动的合成", "composition_of_motion", 3),
    ("运动的分解", "resolution_of_motion", 3),
    ("平抛运动", "horizontal_projectile_motion", 2),
    ("圆周运动", "circular_motion", 2),
    ("匀速圆周运动", "uniform_circular_motion", 2),
    ("线速度", "linear_velocity", 2),
    ("角速度", "angular_velocity", 2),
    ("周期", "period", 1),
    ("频率", "frequency", 1),
    ("向心加速度", "centripetal_acceleration", 2),
    ("向心力", "centripetal_force", 2),
    ("万有引力", "universal_gravitation", 2),
    ("万有引力定律", "law_of_universal_gravitation", 3),
    ("重力加速度", "gravitational_acceleration", 2),
    ("宇宙速度", "cosmic_velocity", 3),
    ("第一宇宙速度", "first_cosmic_velocity", 3),
    ("功", "work", 1),
    ("正功", "positive_work", 2),
    ("负功", "negative_work", 2),
    ("功率", "power", 1),
    ("动能", "kinetic_energy", 1),
    ("重力势能", "gravitational_potential_energy", 2),
    ("弹性势能", "elastic_potential_energy", 2),
    ("机械能", "mechanical_energy", 1),
    ("动能定理", "work_energy_theorem", 2),
    ("机械能守恒定律", "law_of_conservation_of_mechanical_energy", 3),
    ("动量", "momentum", 2),
    ("冲量", "impulse", 2),
    ("动量定理", "momentum_theorem", 3),
    ("动量守恒定律", "law_of_conservation_of_momentum", 3),
    ("碰撞", "collision", 2),
    ("弹性碰撞", "elastic_collision", 3),
    ("非弹性碰撞", "inelastic_collision", 3),
    ("简谐运动", "simple_harmonic_motion", 3),
    ("振幅", "amplitude", 2),
    ("机械振动", "mechanical_vibration", 2),
    ("机械波", "mechanical_wave", 2),
    ("横波", "transverse_wave", 2),
    ("纵波", "longitudinal_wave", 2),
    ("波长", "wavelength", 2),
    ("波速", "wave_speed", 2),
    ("波的干涉", "wave_interference", 3),
    ("波的衍射", "wave_diffraction", 3),
])


PHYSICS_ELECTROMAGNETISM = rows([
    ("电荷", "electric_charge", 1),
    ("正电荷", "positive_charge", 1),
    ("负电荷", "negative_charge", 1),
    ("元电荷", "elementary_charge", 2),
    ("电荷量", "quantity_of_charge", 2),
    ("电荷守恒定律", "law_of_conservation_of_charge", 2),
    ("静电现象", "electrostatic_phenomenon", 2),
    ("摩擦起电", "charging_by_friction", 2),
    ("感应起电", "charging_by_induction", 3),
    ("验电器", "electroscope", 2),
    ("库仑定律", "coulombs_law", 2),
    ("电场", "electric_field", 1),
    ("电场强度", "electric_field_strength", 2),
    ("电场线", "electric_field_line", 2),
    ("匀强电场", "uniform_electric_field", 2),
    ("电势能", "electric_potential_energy", 2),
    ("电势", "electric_potential", 2),
    ("电势差", "potential_difference", 2),
    ("电压", "voltage", 1),
    ("等势面", "equipotential_surface", 3),
    ("电容", "capacitance", 2),
    ("电容器", "capacitor", 2),
    ("平行板电容器", "parallel_plate_capacitor", 3),
    ("电流", "electric_current", 1),
    ("恒定电流", "steady_current", 2),
    ("电路", "electric_circuit", 1),
    ("电源", "power_source", 1),
    ("电动势", "electromotive_force", 2),
    ("内阻", "internal_resistance", 2),
    ("外电路", "external_circuit", 2),
    ("闭合电路", "closed_circuit", 2),
    ("电阻", "resistance", 1),
    ("电阻率", "resistivity", 2),
    ("欧姆定律", "ohms_law", 1),
    ("串联电路", "series_circuit", 2),
    ("并联电路", "parallel_circuit", 2),
    ("滑动变阻器", "sliding_rheostat", 3),
    ("电功", "electric_work", 1),
    ("电功率", "electric_power", 1),
    ("焦耳定律", "joules_law", 2),
    ("磁场", "magnetic_field", 1),
    ("磁感线", "magnetic_field_line", 2),
    ("磁感应强度", "magnetic_flux_density", 2),
    ("匀强磁场", "uniform_magnetic_field", 2),
    ("安培力", "ampere_force", 2),
    ("洛伦兹力", "lorentz_force", 3),
    ("磁通量", "magnetic_flux", 2),
    ("电磁感应", "electromagnetic_induction", 2),
    ("感应电流", "induced_current", 2),
    ("感应电动势", "induced_emf", 3),
    ("法拉第电磁感应定律", "faradays_law_of_electromagnetic_induction", 3),
    ("楞次定律", "lenzs_law", 3),
    ("自感", "self_induction", 3),
    ("互感", "mutual_induction", 3),
    ("交变电流", "alternating_current", 2),
    ("有效值", "effective_value", 2),
    ("变压器", "transformer", 2),
    ("电磁波", "electromagnetic_wave", 2),
    ("电磁场", "electromagnetic_field", 2),
])


PHYSICS_THERMAL = rows([
    ("分子", "molecule", 1),
    ("分子动理论", "molecular_kinetic_theory", 2),
    ("热运动", "thermal_motion", 1),
    ("布朗运动", "brownian_motion", 3),
    ("扩散", "diffusion", 2),
    ("温度", "temperature", 1),
    ("热力学温度", "thermodynamic_temperature", 2),
    ("摄氏温度", "celsius_temperature", 2),
    ("内能", "internal_energy", 1),
    ("热量", "heat", 1),
    ("热传递", "heat_transfer", 2),
    ("热平衡", "thermal_equilibrium", 2),
    ("热容量", "heat_capacity", 2),
    ("比热容", "specific_heat_capacity", 2),
    ("热值", "calorific_value", 2),
    ("熔化", "melting", 1),
    ("凝固", "solidification", 1),
    ("汽化", "vaporization", 1),
    ("液化", "liquefaction", 1),
    ("升华", "sublimation", 2),
    ("凝华", "deposition", 2),
    ("晶体", "crystal", 2),
    ("非晶体", "amorphous_solid", 2),
    ("熔点", "melting_point", 1),
    ("沸点", "boiling_point", 1),
    ("气体", "gas", 1),
    ("理想气体", "ideal_gas", 2),
    ("气体压强", "gas_pressure", 2),
    ("气体体积", "gas_volume", 2),
    ("气体温度", "gas_temperature", 2),
    ("玻意耳定律", "boyles_law", 3),
    ("查理定律", "charles_law", 3),
    ("盖吕萨克定律", "gay_lussacs_law", 3),
    ("理想气体状态方程", "ideal_gas_equation", 3),
    ("等温变化", "isothermal_process", 2),
    ("等容变化", "isochoric_process", 2),
    ("等压变化", "isobaric_process", 2),
    ("热力学第一定律", "first_law_of_thermodynamics", 3),
    ("做功", "doing_work", 2),
    ("吸热", "heat_absorption", 1),
    ("放热", "heat_release", 1),
    ("能量守恒", "conservation_of_energy", 2),
])


PHYSICS_OPTICS = rows([
    ("光源", "light_source", 1),
    ("光线", "light_ray", 1),
    ("光速", "speed_of_light", 1),
    ("光的直线传播", "rectilinear_propagation_of_light", 2),
    ("影", "shadow", 1),
    ("小孔成像", "pinhole_imaging", 2),
    ("反射", "reflection", 1),
    ("反射定律", "law_of_reflection", 2),
    ("入射光线", "incident_ray", 2),
    ("反射光线", "reflected_ray", 2),
    ("法线", "normal_line", 2),
    ("入射角", "angle_of_incidence", 2),
    ("反射角", "angle_of_reflection", 2),
    ("平面镜", "plane_mirror", 2),
    ("虚像", "virtual_image", 2),
    ("实像", "real_image", 2),
    ("折射", "refraction", 1),
    ("折射定律", "law_of_refraction", 2),
    ("折射率", "refractive_index", 2),
    ("全反射", "total_internal_reflection", 3),
    ("临界角", "critical_angle", 3),
    ("透镜", "lens", 1),
    ("凸透镜", "convex_lens", 2),
    ("凹透镜", "concave_lens", 2),
    ("焦点", "focus", 2),
    ("焦距", "focal_length", 2),
    ("光心", "optical_center", 2),
    ("主光轴", "principal_axis", 2),
    ("像距", "image_distance", 2),
    ("物距", "object_distance", 2),
    ("放大率", "magnification", 2),
    ("显微镜", "microscope", 2),
    ("望远镜", "telescope", 2),
    ("光的色散", "dispersion_of_light", 2),
    ("棱镜", "prism", 2),
    ("光谱", "spectrum", 2),
    ("干涉", "interference", 2),
    ("衍射", "diffraction", 2),
    ("偏振", "polarization", 3),
])


MATH_SETS_FUNCTIONS = rows([
    ("集合", "set", 1),
    ("元素", "element", 1),
    ("子集", "subset", 1),
    ("真子集", "proper_subset", 2),
    ("空集", "empty_set", 1),
    ("全集", "universal_set", 2),
    ("交集", "intersection", 1),
    ("并集", "union", 1),
    ("补集", "complement", 2),
    ("充分条件", "sufficient_condition", 2),
    ("必要条件", "necessary_condition", 2),
    ("充要条件", "necessary_and_sufficient_condition", 2),
    ("全称量词", "universal_quantifier", 3),
    ("存在量词", "existential_quantifier", 3),
    ("函数", "function", 1),
    ("定义域", "domain", 1),
    ("值域", "range", 1),
    ("对应关系", "correspondence", 2),
    ("函数图像", "graph_of_function", 1),
    ("单调性", "monotonicity", 2),
    ("奇偶性", "parity", 2),
    ("周期性", "periodicity", 2),
    ("零点", "zero_of_function", 2),
    ("一次函数", "linear_function", 1),
    ("二次函数", "quadratic_function", 1),
    ("幂函数", "power_function", 2),
    ("指数函数", "exponential_function", 2),
    ("对数函数", "logarithmic_function", 2),
    ("反函数", "inverse_function", 2),
    ("复合函数", "composite_function", 2),
    ("分段函数", "piecewise_function", 2),
    ("函数模型", "function_model", 2),
    ("导数", "derivative", 2),
    ("导函数", "derived_function", 2),
    ("切线", "tangent_line", 2),
    ("极大值", "local_maximum", 2),
    ("极小值", "local_minimum", 2),
    ("最大值", "maximum_value", 1),
    ("最小值", "minimum_value", 1),
])


MATH_TRIG_VECTORS = rows([
    ("角", "angle", 1),
    ("弧度", "radian", 2),
    ("弧度制", "radian_measure", 2),
    ("任意角", "arbitrary_angle", 2),
    ("终边", "terminal_side", 2),
    ("单位圆", "unit_circle", 2),
    ("正弦", "sine", 1),
    ("余弦", "cosine", 1),
    ("正切", "tangent", 1),
    ("三角函数", "trigonometric_function", 1),
    ("诱导公式", "reduction_formula", 2),
    ("同角三角函数关系", "fundamental_trigonometric_identity", 3),
    ("两角和公式", "sum_formula", 2),
    ("两角差公式", "difference_formula", 2),
    ("二倍角公式", "double_angle_formula", 2),
    ("正弦定理", "law_of_sines", 2),
    ("余弦定理", "law_of_cosines", 2),
    ("解三角形", "solving_triangle", 2),
    ("向量", "vector", 1),
    ("平面向量", "plane_vector", 1),
    ("零向量", "zero_vector", 2),
    ("单位向量", "unit_vector", 2),
    ("相等向量", "equal_vectors", 2),
    ("相反向量", "opposite_vectors", 2),
    ("共线向量", "collinear_vectors", 2),
    ("向量加法", "vector_addition", 2),
    ("向量减法", "vector_subtraction", 2),
    ("数乘向量", "scalar_multiplication_of_vector", 2),
    ("平面向量基本定理", "fundamental_theorem_of_plane_vectors", 3),
    ("向量坐标", "vector_coordinates", 2),
    ("数量积", "dot_product", 2),
    ("夹角", "included_angle", 2),
])


MATH_GEOMETRY = rows([
    ("直线", "line", 1),
    ("射线", "ray", 1),
    ("线段", "line_segment", 1),
    ("平面", "plane", 1),
    ("空间几何体", "solid_geometry", 2),
    ("棱柱", "prism", 2),
    ("棱锥", "pyramid", 2),
    ("棱台", "frustum_of_pyramid", 3),
    ("圆柱", "cylinder", 2),
    ("圆锥", "cone", 2),
    ("圆台", "frustum_of_cone", 3),
    ("球", "sphere", 1),
    ("三视图", "three_views", 2),
    ("直观图", "pictorial_drawing", 2),
    ("平行", "parallel", 1),
    ("垂直", "perpendicular", 1),
    ("异面直线", "skew_lines", 3),
    ("线面平行", "line_plane_parallelism", 2),
    ("面面平行", "plane_plane_parallelism", 2),
    ("线面垂直", "line_plane_perpendicularity", 2),
    ("面面垂直", "plane_plane_perpendicularity", 2),
    ("空间向量", "space_vector", 2),
    ("空间直角坐标系", "space_rectangular_coordinate_system", 3),
    ("直线方程", "equation_of_line", 2),
    ("斜率", "slope", 1),
    ("倾斜角", "angle_of_inclination", 2),
    ("截距", "intercept", 2),
    ("圆", "circle", 1),
    ("圆的方程", "equation_of_circle", 2),
    ("圆锥曲线", "conic_section", 3),
    ("椭圆", "ellipse", 2),
    ("双曲线", "hyperbola", 2),
    ("抛物线", "parabola", 2),
    ("焦点", "focus", 2),
    ("准线", "directrix", 3),
    ("离心率", "eccentricity", 3),
])


MATH_SEQUENCES_INEQUALITIES = rows([
    ("数列", "sequence", 1),
    ("通项公式", "general_term_formula", 2),
    ("递推公式", "recurrence_formula", 2),
    ("等差数列", "arithmetic_sequence", 1),
    ("公差", "common_difference", 2),
    ("等差中项", "arithmetic_mean", 2),
    ("等比数列", "geometric_sequence", 1),
    ("公比", "common_ratio", 2),
    ("等比中项", "geometric_mean", 2),
    ("前n项和", "sum_of_first_n_terms", 2),
    ("不等式", "inequality", 1),
    ("一元二次不等式", "quadratic_inequality_in_one_variable", 2),
    ("基本不等式", "basic_inequality", 2),
    ("线性规划", "linear_programming", 3),
    ("可行域", "feasible_region", 3),
    ("目标函数", "objective_function", 3),
    ("最优解", "optimal_solution", 3),
    ("复数", "complex_number", 2),
    ("虚数单位", "imaginary_unit", 2),
    ("实部", "real_part", 2),
    ("虚部", "imaginary_part", 2),
    ("共轭复数", "conjugate_complex_number", 2),
    ("复平面", "complex_plane", 2),
    ("数学归纳法", "mathematical_induction", 3),
])


MATH_PROBABILITY_STATISTICS = rows([
    ("样本", "sample", 1),
    ("总体", "population", 1),
    ("个体", "individual", 1),
    ("容量", "sample_size", 2),
    ("抽样", "sampling", 2),
    ("简单随机抽样", "simple_random_sampling", 2),
    ("分层抽样", "stratified_sampling", 2),
    ("频数", "frequency_count", 2),
    ("频率", "relative_frequency", 1),
    ("平均数", "mean", 1),
    ("中位数", "median", 1),
    ("众数", "mode", 1),
    ("极差", "range_of_data", 2),
    ("方差", "variance", 2),
    ("标准差", "standard_deviation", 2),
    ("散点图", "scatter_plot", 2),
    ("相关性", "correlation", 2),
    ("回归直线", "regression_line", 3),
    ("随机事件", "random_event", 1),
    ("必然事件", "certain_event", 2),
    ("不可能事件", "impossible_event", 2),
    ("概率", "probability", 1),
    ("古典概型", "classical_probability_model", 2),
    ("互斥事件", "mutually_exclusive_events", 2),
    ("对立事件", "complementary_events", 2),
    ("条件概率", "conditional_probability", 3),
    ("独立事件", "independent_events", 3),
    ("二项分布", "binomial_distribution", 3),
    ("正态分布", "normal_distribution", 3),
])


FILES = {
    WORDS_DIR / "物理" / "入门模式：高中物理" / "high_school_mechanics_terms.csv": PHYSICS_MECHANICS,
    WORDS_DIR / "物理" / "入门模式：高中物理" / "high_school_electromagnetism_terms.csv": PHYSICS_ELECTROMAGNETISM,
    WORDS_DIR / "物理" / "入门模式：高中物理" / "high_school_thermal_terms.csv": PHYSICS_THERMAL,
    WORDS_DIR / "物理" / "入门模式：高中物理" / "high_school_optics_terms.csv": PHYSICS_OPTICS,
    WORDS_DIR / "数学" / "入门模式：高中数学" / "high_school_sets_functions_terms.csv": MATH_SETS_FUNCTIONS,
    WORDS_DIR / "数学" / "入门模式：高中数学" / "high_school_trigonometry_vectors_terms.csv": MATH_TRIG_VECTORS,
    WORDS_DIR / "数学" / "入门模式：高中数学" / "high_school_geometry_terms.csv": MATH_GEOMETRY,
    WORDS_DIR / "数学" / "入门模式：高中数学" / "high_school_sequences_inequalities_terms.csv": MATH_SEQUENCES_INEQUALITIES,
    WORDS_DIR / "数学" / "入门模式：高中数学" / "high_school_probability_statistics_terms.csv": MATH_PROBABILITY_STATISTICS,
}


def write_file(path, items):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, lineterminator="\n")
        writer.writerow(HEADER)
        for index, (cn, difficulty, english) in enumerate(items, 1):
            initials = make_initials(cn)
            pinyin = make_pinyin(cn)
            writer.writerow([
                index,
                cn,
                difficulty,
                initials,
                len(initials),
                english,
                len(english),
                pinyin,
                len(pinyin),
            ])
    return len(items)


def main():
    for path, items in FILES.items():
        count = write_file(path, items)
        print(f"{path.relative_to(ROOT)}: {count}")


if __name__ == "__main__":
    main()
