import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORDS_DIR = ROOT / "words"
PHYSICS_SIMPLE_DIR = WORDS_DIR / "物理" / "简单模式：普通物理"

HEADER = [
    "编号",
    "概念中文名",
    "中文首字母",
    "中文首字母串长度",
    "概念英文名",
    "英文字符串长度",
    "概念中文拼音",
    "拼音字符串长度",
]


TABLES = {
    "mechanics_terms.csv": """
位移|WY|displacement|weiyi
路程|LC|path_length|lucheng
位置矢量|WZSL|position_vector|weizhishiliang
参考系|CKX|reference_frame|cankaoxi
质点|ZD|particle|zhidian
坐标系|ZBX|coordinate_system|zuobiaoxi
运动|YD|motion|yundong
速度|SD|velocity|sudu
速率|SL|speed|sulv
平均速度|PJSD|average_velocity|pingjunsudu
瞬时速度|SSSD|instantaneous_velocity|shunshisudu
平均速率|PJSL|average_speed|pingjunsulv
瞬时速率|SSSL|instantaneous_speed|shunshisulv
加速度|JSD|acceleration|jiasudu
切向加速度|QXJSD|tangential_acceleration|qiexiangjiasudu
法向加速度|FXJSD|normal_acceleration|faxiangjiasudu
角位移|JWY|angular_displacement|jiaoweiyi
角速度|JSD|angular_velocity|jiaosudu
角加速度|JJSD|angular_acceleration|jiaojiasudu
直线运动|ZXYD|rectilinear_motion|zhixianyundong
曲线运动|QXYD|curvilinear_motion|quxianyundong
匀速运动|YSYD|uniform_motion|yunsuyundong
变速运动|BSYD|variable_motion|biansuyundong
加速运动|JSYD|accelerating_motion|jiasuyundong
减速运动|JSYD|decelerating_motion|jiansuyundong
匀速直线运动|YSZXYD|uniform_rectilinear_motion|yunsuzhixianyundong
匀变速直线运动|YBSZXYD|uniformly_accelerated_rectilinear_motion|yunbiansuzhixianyundong
自由落体运动|ZYLTDYD|free_fall_motion|ziyouloutiyundong
抛体运动|PTYD|projectile_motion|paotiyundong
平抛运动|PPYD|horizontal_projectile_motion|pingpaoyundong
斜抛运动|XPYD|oblique_projectile_motion|xiepaoyundong
圆周运动|YZYD|circular_motion|yuanzhouyundong
匀速圆周运动|YSYZYD|uniform_circular_motion|yunsuyuanzhouyundong
相对速度|XDSD|relative_velocity|xiangduisudu
伽利略变换|JLLBH|galilean_transformation|jialiluebianhuan
惯性系|GXX|inertial_frame|guanxingxi
非惯性系|FGXX|non_inertial_frame|feiguanxingxi
惯性|GX|inertia|guanxing
质量|ZL|mass|zhiliang
力|L|force|li
合力|HL|resultant_force|heli
分力|FL|component_force|fenli
重力|ZL|gravity|zhongli
弹力|TL|elastic_force|tanli
张力|ZL|tension|zhangli
支持力|ZCL|normal_force|zhichili
摩擦力|MCL|friction_force|mocali
静摩擦力|JMCL|static_friction_force|jingmocali
滑动摩擦力|HDMCL|kinetic_friction_force|huadongmocali
摩擦因数|MCYS|coefficient_of_friction|mocayinsu
牛顿第一定律|NDDYDL|newtons_first_law|niudundiyidinglv
牛顿第二定律|NDDEDL|newtons_second_law|niudundierdinglv
牛顿第三定律|NDDSDL|newtons_third_law|niudundisandinglv
惯性力|GXL|inertial_force|guanxingli
离心力|LXL|centrifugal_force|lixinli
向心力|XXL|centripetal_force|xiangxinli
向心加速度|XXJSD|centripetal_acceleration|xiangxinjiasudu
动量|DL|momentum|dongliang
冲量|CL|impulse|chongliang
动量定理|DLDL|impulse_momentum_theorem|dongliangdingli
动量守恒定律|DLSHDL|law_of_conservation_of_momentum|dongliangshouhengdinglv
质心|ZX|center_of_mass|zhixin
质心系|ZXX|center_of_mass_frame|zhixinxi
质心运动定理|ZXYDDL|theorem_of_center_of_mass_motion|zhixinyundongdingli
碰撞|PZ|collision|pengzhuang
弹性碰撞|TXPZ|elastic_collision|tanxingpengzhuang
非弹性碰撞|FTXPZ|inelastic_collision|feitanxingpengzhuang
完全非弹性碰撞|WQFTXPZ|perfectly_inelastic_collision|wanquanfeitanxingpengzhuang
功|G|work|gong
功率|GL|power|gonglv
动能|DN|kinetic_energy|dongneng
动能定理|DNDL|work_energy_theorem|dongnengdingli
势能|SN|potential_energy|shineng
重力势能|ZLSN|gravitational_potential_energy|zhonglishineng
弹性势能|TXSN|elastic_potential_energy|tanxingshineng
保守力|BSL|conservative_force|baoshouli
非保守力|FBSL|non_conservative_force|feibaoshouli
机械能|JXN|mechanical_energy|jixieneng
机械能守恒定律|JXNSHDL|law_of_conservation_of_mechanical_energy|jixienengshouhengdinglv
力矩|LJ|torque|liju
力臂|LB|lever_arm|libi
角动量|JDL|angular_momentum|jiaodongliang
角动量定理|JDLDL|angular_momentum_theorem|jiaodongliangdingli
角动量守恒定律|JDLSHDL|law_of_conservation_of_angular_momentum|jiaodongliangshouhengdinglv
转动|ZD|rotation|zhuandong
平动|PD|translation|pingdong
转动惯量|ZDGL|moment_of_inertia|zhuandongguanliang
刚体|GT|rigid_body|gangti
刚体定轴转动|GTDZZD|fixed_axis_rotation_of_rigid_body|gangtidingzhouzhuandong
转动动能|ZDDN|rotational_kinetic_energy|zhuandongdongneng
转动定律|ZDDL|law_of_rotation|zhuandongdinglv
平行轴定理|PXZDL|parallel_axis_theorem|pingxingzhoudingli
垂直轴定理|CZZDL|perpendicular_axis_theorem|chuizhizhoutingli
滚动|GD|rolling_motion|gundong
纯滚动|CGD|pure_rolling|chungundong
进动|JD|precession|jindong
力偶|LO|couple|liou
力偶矩|LOJ|couple_moment|liouju
平衡|PH|equilibrium|pingheng
静力平衡|JLPH|static_equilibrium|jinglipingheng
振动|ZD|vibration|zhendong
简谐运动|JXYD|simple_harmonic_motion|jianxieyundong
简谐振动|JXZD|simple_harmonic_oscillation|jianxiezhendong
振幅|ZF|amplitude|zhenfu
周期|ZQ|period|zhouqi
频率|PL|frequency|pinlv
角频率|JPL|angular_frequency|jiaopinlv
相位|XW|phase|xiangwei
初相位|CXW|initial_phase|chuxiangwei
回复力|HFL|restoring_force|huifuli
弹簧|TH|spring|tanhuang
弹簧振子|THZZ|spring_oscillator|tanhuangzhenzi
摆|B|pendulum|bai
单摆|DB|simple_pendulum|danbai
物理摆|WLB|physical_pendulum|wulibai
阻尼|ZN|damping|zuni
阻尼振动|ZNZD|damped_oscillation|zunizhendong
受迫振动|SPZD|forced_oscillation|shoupozhendong
共振|GZ|resonance|gongzhen
波|B|wave|bo
波动|BD|wave_motion|bodong
机械波|JXB|mechanical_wave|jixiebo
横波|HB|transverse_wave|hengbo
纵波|ZB|longitudinal_wave|zongbo
波长|BC|wavelength|bochang
波速|BS|wave_speed|bosu
波数|BS|wave_number|boshu
波函数|BHS|wave_function|bohanshu
波的叠加原理|BDDJYL|principle_of_superposition_of_waves|bodediejiayuanli
驻波|ZB|standing_wave|zhubo
波节|BJ|node|bojie
波腹|BF|antinode|bofu
多普勒效应|DPLXY|doppler_effect|duopulexiaoying
波源|BY|wave_source|boyuan
波面|BM|wavefront|bomian
波线|BX|wave_ray|boxian
振源|ZY|vibration_source|zhenyuan
介质|JZ|medium|jiezhi
振子|ZZ|oscillator|zhenzi
流体|LT|fluid|liuti
理想流体|LXLT|ideal_fluid|lixiangliuti
密度|MD|density|midu
压强|YQ|pressure|yaqiang
浮力|FL|buoyancy|fuli
阿基米德原理|AJMDYL|archimedes_principle|ajimideyuanli
连续性方程|LXXFC|continuity_equation|lianxuxingfangcheng
伯努利方程|BNLFC|bernoulli_equation|bonulifangcheng
黏滞力|NZL|viscous_force|nianzili
黏度|ND|viscosity|niandu
弹性形变|TXXB|elastic_deformation|tanxingxingbian
应力|YL|stress|yingli
应变|YB|strain|yingbian
杨氏模量|YSML|youngs_modulus|yangshimoliang
剪切模量|JQML|shear_modulus|jianqiemoliang
体积模量|TJML|bulk_modulus|tijimoliang
矢量|SL|vector|shiliang
标量|BL|scalar|biaoliang
分量|FL|component|fenliang
坐标|ZB|coordinate|zuobiao
轨迹|GJ|trajectory|guiji
弧长|HC|arc_length|huchang
半径|BJ|radius|banjing
角度|JD|angle|jiaodu
弧度|HD|radian|hudu
圆心|YX|center_of_circle|yuanxin
切线|QX|tangent|qiexian
法线|FX|normal_line|faxian
斜面|XM|inclined_plane|xiemian
滑轮|HL|pulley|hualun
杠杆|GG|lever|ganggan
支点|ZD|fulcrum|zhidian
力学|LX|mechanics|lixue
动力学|DLX|dynamics|donglixue
运动学|YDX|kinematics|yundongxue
静力学|JLX|statics|jinglixue
流体力学|LTLX|fluid_mechanics|liutilixue
""",
    "electromagnetism_terms.csv": """
电磁学|DCX|electromagnetism|diancixue
电荷|DH|electric_charge|dianhe
正电荷|ZDH|positive_charge|zhengdianhe
负电荷|FDH|negative_charge|fudianhe
点电荷|DDH|point_charge|diandianhe
试探电荷|STDH|test_charge|shitandianhe
电荷守恒定律|DHSHDL|law_of_conservation_of_charge|dianheshouhengdinglv
库仑定律|KLDL|coulombs_law|kulundinglv
库仑力|KLL|coulomb_force|kulunli
电场|DC|electric_field|dianchang
电场强度|DCQD|electric_field_strength|dianchangqiangdu
电场线|DCX|electric_field_line|dianchangxian
匀强电场|YQDC|uniform_electric_field|yunqiangdianchang
电偶极子|DOJZ|electric_dipole|dianoujizi
电偶极矩|DOJJ|electric_dipole_moment|dianoujiju
电通量|DTL|electric_flux|diantongliang
高斯定理|GSDL|gauss_theorem|gaosidingli
高斯面|GSM|gaussian_surface|gaosimian
电势|DS|electric_potential|dianshi
电势差|DSC|potential_difference|dianshicha
电压|DY|voltage|dianya
等势面|DSM|equipotential_surface|dengshimian
电势能|DSN|electric_potential_energy|dianshineng
静电场|JDC|electrostatic_field|jingdianchang
静电平衡|JDPH|electrostatic_equilibrium|jingdianpingheng
静电屏蔽|JDPB|electrostatic_shielding|jingdianpingbi
导体|DT|conductor|daoti
绝缘体|JYT|insulator|jueyuanti
电介质|DJZ|dielectric|dianjiezhi
极化|JH|polarization|jihua
介电常数|JDCZ|dielectric_constant|jiedianchangshu
相对介电常数|XDJDCZ|relative_dielectric_constant|xiangduijiedianchangshu
电容|DR|capacitance|dianrong
电容器|DRQ|capacitor|dianrongqi
平行板电容器|PXBDRQ|parallel_plate_capacitor|pingxingbandianrongqi
电容器能量|DRQNL|energy_of_capacitor|dianrongqinengliang
电流|DL|electric_current|dianliu
电流强度|DLQD|current_intensity|dianliuqiangdu
电流密度|DLMD|current_density|dianliumidu
稳恒电流|WHDL|steady_current|wenhengdianliu
直流电流|ZLDL|direct_current|zhiliudianliu
交流电流|JLDL|alternating_current|jiaoliudianliu
电源|DY|power_source|dianyuan
电动势|DDS|electromotive_force|diandongshi
端电压|DDY|terminal_voltage|duandianya
电阻|DZ|resistance|dianzu
电阻器|DZQ|resistor|dianzuqi
电阻率|DZL|resistivity|dianzulu
电导|DD|conductance|diandao
电导率|DDL|conductivity|diandaolv
欧姆定律|OMDL|ohms_law|oumudinglv
焦耳定律|JEDL|joules_law|jiaoerdinglv
焦耳热|JER|joule_heat|jiaoerre
电功|DG|electric_work|diangong
电功率|DGL|electric_power|diangonglv
串联电路|CLDL|series_circuit|chuanliandianlu
并联电路|BLDL|parallel_circuit|bingliandianlu
混联电路|HLDL|compound_circuit|hunliandianlu
基尔霍夫定律|JEHFDL|kirchhoffs_law|jierhuofudinglv
节点电流定律|JDDL|junction_rule|jiediandianliudinglv
回路电压定律|HLDYDL|loop_rule|huiludianyadinglv
闭合电路欧姆定律|BHDLOMDL|ohms_law_for_closed_circuit|bihedianluoumudinglv
磁场|CC|magnetic_field|cichang
磁感应强度|CGYQD|magnetic_flux_density|ciganyingqiangdu
磁感线|CGX|magnetic_field_line|ciganxian
磁通量|CTL|magnetic_flux|citongliang
磁矩|CJ|magnetic_moment|ciju
磁偶极子|COJZ|magnetic_dipole|cioujizi
洛伦兹力|LLZL|lorentz_force|luolunzili
安培力|APL|ampere_force|anpeili
安培定律|APDL|amperes_law|anpeidinglv
毕奥萨伐尔定律|BASFEDL|biot_savart_law|biaosafaerdinglv
载流导线|ZLDX|current_carrying_wire|zailiudaoxian
载流线圈|ZLXQ|current_carrying_coil|zailiuxianquan
通电螺线管|TDLXG|current_carrying_solenoid|tongdianluoxianguan
霍尔效应|HEXY|hall_effect|huoerxiaoying
磁介质|CJZ|magnetic_medium|cijiezhi
磁化|CH|magnetization|cihua
磁导率|CDL|magnetic_permeability|cidaolv
相对磁导率|XDCDL|relative_permeability|xiangduicidaolv
顺磁性|SCX|paramagnetism|shuncixing
抗磁性|KCX|diamagnetism|kangcixing
铁磁性|TCX|ferromagnetism|tiecixing
磁滞|CZ|hysteresis|cizhi
磁滞回线|CZHX|hysteresis_loop|cizhihuixian
电磁感应|DCGY|electromagnetic_induction|dianciganying
感应电动势|GYDDS|induced_electromotive_force|ganyingdiandongshi
感应电流|GYDL|induced_current|ganyingdianliu
法拉第电磁感应定律|FLDDCGYDL|faradays_law_of_electromagnetic_induction|faladidianciganyingdinglv
楞次定律|LCDL|lenzs_law|lengcidinglv
自感|ZG|self_inductance|zigan
互感|HG|mutual_inductance|hugan
电感|DG|inductance|diangan
电感器|DGQ|inductor|dianganqi
磁场能量|CCNL|energy_of_magnetic_field|cichangnengliang
涡电流|WDL|eddy_current|wodianliu
位移电流|WYDL|displacement_current|weiyidianliu
麦克斯韦方程组|MKSWFCZ|maxwell_equations|maikesiweifangchengzu
电磁场|DCC|electromagnetic_field|diancichang
电磁波|DCB|electromagnetic_wave|diancibo
电磁振荡|DCZD|electromagnetic_oscillation|diancizhendang
振荡电路|ZDDL|oscillating_circuit|zhendangdianlu
交流电路|JLDL|alternating_current_circuit|jiaoliudianlu
阻抗|ZK|impedance|zukang
容抗|RK|capacitive_reactance|rongkang
感抗|GK|inductive_reactance|gankang
相位差|XWC|phase_difference|xiangweicha
有效值|YXZ|root_mean_square_value|youxiaozhi
谐振|XZ|resonance|xiezhen
变压器|BYQ|transformer|bianyaqi
理想变压器|LXBYQ|ideal_transformer|lixiangbianyaqi
整流|ZL|rectification|zhengliu
示波器|SBQ|oscilloscope|shiboqi
电子枪|DZQ|electron_gun|dianziqiang
阴极射线|YJSX|cathode_ray|yinjishexian
""",
    "optics_terms.csv": """
光学|GX|optics|guangxue
光|G|light|guang
光线|GX|light_ray|guangxian
光束|GS|light_beam|guangshu
光源|GY|light_source|guangyuan
点光源|DGY|point_light_source|dianguangyuan
波面|BM|wavefront|bomian
光程|GC|optical_path|guangcheng
光程差|GCC|optical_path_difference|guangchengcha
相干光|XGG|coherent_light|xianggan guang
相干光源|XGGY|coherent_light_source|xiangganguangyuan
光强|GQ|light_intensity|guangqiang
照度|ZD|illuminance|zhaodu
发光强度|FGQD|luminous_intensity|faguangqiangdu
光通量|GTL|luminous_flux|guangtongliang
反射|FS|reflection|fanshe
反射定律|FSDL|law_of_reflection|fanshedinglv
入射角|RSJ|angle_of_incidence|rushejiao
反射角|FSJ|angle_of_reflection|fanshejiao
法线|FX|normal_line|faxian
平面镜|PMJ|plane_mirror|pingmianjing
球面镜|QMJ|spherical_mirror|qiumianjing
凹面镜|AMJ|concave_mirror|aomianjing
凸面镜|TMJ|convex_mirror|tumianjing
焦点|JD|focus|jiaodian
焦距|JJ|focal_length|jiaoju
主轴|ZZ|principal_axis|zhuzhou
物距|WJ|object_distance|wuju
像距|XJ|image_distance|xiangju
实像|SX|real_image|shixiang
虚像|XX|virtual_image|xuxiang
放大率|FDL|magnification|fangdalv
折射|ZS|refraction|zheshe
折射定律|ZSDL|law_of_refraction|zheshedinglv
斯涅尔定律|SNEDL|snells_law|sinieerdinglv
折射率|ZSL|refractive_index|zheshelv
绝对折射率|JDZSL|absolute_refractive_index|jueduizheshelv
相对折射率|XDZSL|relative_refractive_index|xiangduizheshelv
全反射|QFS|total_internal_reflection|quanfanshe
临界角|LJJ|critical_angle|linjiejiao
色散|SS|dispersion|sesan
棱镜|LJ|prism|lengjing
透镜|TJ|lens|toujing
薄透镜|BTJ|thin_lens|baotoujing
凸透镜|TTJ|convex_lens|tutoujing
凹透镜|ATJ|concave_lens|aotoujing
会聚透镜|HJTJ|converging_lens|huijutoujing
发散透镜|FSTJ|diverging_lens|fasantoujing
透镜公式|TJGS|lens_formula|toujinggongshi
光焦度|GJD|optical_power|guangjiaodu
眼睛|YJ|eye|yanjing
近视|JS|myopia|jinshi
远视|YS|hyperopia|yuanshi
显微镜|XWJ|microscope|xianweijing
望远镜|WYJ|telescope|wangyuanjing
照相机|ZXJ|camera|zhaoxiangji
光阑|GL|aperture_stop|guanglan
孔径|KJ|aperture|kongjing
光的干涉|GDGS|interference_of_light|guangdeganshe
干涉|GS|interference|ganshe
明纹|MW|bright_fringe|mingwen
暗纹|AW|dark_fringe|anwen
条纹间距|TWJJ|fringe_spacing|tiaowenjianju
杨氏双缝干涉|YSSFGS|youngs_double_slit_interference|yangshishuangfengganshe
双缝|SF|double_slit|shuangfeng
薄膜干涉|BMGS|thin_film_interference|baomoganshe
等厚干涉|DHGS|equal_thickness_interference|denghouganshe
牛顿环|NDH|newtons_rings|niudunhuan
光的衍射|GDYS|diffraction_of_light|guangdeyanshe
衍射|YS|diffraction|yanshe
单缝衍射|DFYS|single_slit_diffraction|danfengyanshe
圆孔衍射|YKYS|circular_aperture_diffraction|yuankongyanshe
衍射光栅|YSGS|diffraction_grating|yansheguangshan
光栅常数|GSCZ|grating_constant|guangshanchangshu
光栅方程|GSFC|grating_equation|guangshanfangcheng
分辨本领|FBBL|resolving_power|fenbianbenling
瑞利判据|RLPJ|rayleigh_criterion|ruilipanju
偏振|PZ|polarization|pianzhen
自然光|ZRG|natural_light|ziranguang
偏振光|PZG|polarized_light|pianzhenguang
线偏振光|XPZG|linearly_polarized_light|xianpianzhenguang
起偏器|QPQ|polarizer|qipianqi
检偏器|JPQ|analyzer|jianpianqi
马吕斯定律|MLSDL|malus_law|malyusidinglv
布儒斯特定律|BRSTDL|brewsters_law|burusitedinglv
布儒斯特角|BRSTJ|brewster_angle|burusitejiao
双折射|SZS|birefringence|shuangzheshe
光轴|GZ|optical_axis|guangzhou
光速|GS|speed_of_light|guangsu
真空光速|ZKGS|speed_of_light_in_vacuum|zhenkongguangsu
光谱|GP|spectrum|guangpu
连续光谱|LXGP|continuous_spectrum|lianxuguangpu
线状光谱|XZGP|line_spectrum|xianzhuangguangpu
吸收光谱|XSGP|absorption_spectrum|xishouguangpu
发射光谱|FSGP|emission_spectrum|fasheguangpu
激光|JG|laser|jiguang
单色光|DSG|monochromatic_light|danseguang
""",
    "thermal_terms.csv": """
热学|RX|thermal_physics|rexue
热|R|heat|re
温度|WD|temperature|wendu
温标|WB|temperature_scale|wenbiao
摄氏温标|SSWB|celsius_scale|sheshiwenbiao
热力学温标|RLXWB|thermodynamic_temperature_scale|relixuewenbiao
绝对温度|JDWD|absolute_temperature|jueduiwendu
热平衡|RPH|thermal_equilibrium|repingheng
热量|RL|quantity_of_heat|reliang
内能|NN|internal_energy|neineng
分子|FZ|molecule|fenzi
原子|YZ|atom|yuanzi
分子动理论|FZDLL|molecular_kinetic_theory|fenzidonglilun
分子热运动|FZRYD|molecular_thermal_motion|fenzireyundong
布朗运动|BLYD|brownian_motion|bulangyundong
扩散|KS|diffusion|kuosan
理想气体|LXQT|ideal_gas|lixiangqiti
气体|QT|gas|qiti
压强|YQ|pressure|yaqiang
体积|TJ|volume|tiji
物质的量|WZDL|amount_of_substance|wuzhideliang
摩尔|ME|mole|moer
摩尔质量|MEZL|molar_mass|moerzhiliang
阿伏伽德罗常数|AFJDLCS|avogadro_constant|afujialuodechangshu
玻尔兹曼常数|BEZMCS|boltzmann_constant|boerzimanchangshu
气体常数|QTCS|gas_constant|qitichangshu
理想气体状态方程|LXQTZTFC|ideal_gas_equation_of_state|lixiangqitizhuangtaifangcheng
状态方程|ZTFC|equation_of_state|zhuangtaifangcheng
等温过程|DWGC|isothermal_process|dengwenguocheng
等压过程|DYGC|isobaric_process|dengyaguocheng
等容过程|DRGC|isochoric_process|dengrongguocheng
绝热过程|JRGC|adiabatic_process|juereguocheng
准静态过程|ZJTGC|quasi_static_process|zhunjingtaiguocheng
循环过程|XHGC|cyclic_process|xunhuanguocheng
状态参量|ZTCL|state_variable|zhuangtaicanliang
状态函数|ZTHS|state_function|zhuangtaihanshu
热力学功|RLXG|thermodynamic_work|relixuegong
热容量|RRL|heat_capacity|rerongliang
比热容|BRR|specific_heat_capacity|birerong
摩尔热容|MERR|molar_heat_capacity|moerrerong
定容热容|DRRR|heat_capacity_at_constant_volume|dingrongrerong
定压热容|DYRR|heat_capacity_at_constant_pressure|dingyarerong
热力学第一定律|RLXDYDL|first_law_of_thermodynamics|relixuediyidinglv
热力学第二定律|RLXDEDL|second_law_of_thermodynamics|relixuedierdinglv
热力学第三定律|RLXDSDL|third_law_of_thermodynamics|relixuedisandinglv
能量守恒定律|NLSHDL|law_of_conservation_of_energy|nengliangshouhengdinglv
热机|RJ|heat_engine|reji
制冷机|ZLJ|refrigerator|zhilengji
热泵|RB|heat_pump|rebeng
卡诺循环|KNXH|carnot_cycle|kanuoxunhuan
卡诺热机|KNRJ|carnot_engine|kanuoreji
热效率|RXL|thermal_efficiency|rexiaolv
熵|S|entropy|shang
熵增原理|SZYL|principle_of_entropy_increase|shangzengyuanli
可逆过程|KNGC|reversible_process|keniguocheng
不可逆过程|BKNGC|irreversible_process|bukeniguocheng
自由膨胀|ZYPZ|free_expansion|ziyoupengzhang
热传递|RCD|heat_transfer|rechuandi
热传导|RCD|heat_conduction|rechuandao
对流|DL|convection|duiliu
热辐射|RFS|thermal_radiation|refushe
导热系数|DRXS|thermal_conductivity|daorexishu
黑体|HT|blackbody|heiti
黑体辐射|HTFS|blackbody_radiation|heitifushe
斯特藩玻尔兹曼定律|STFBEZMDL|stefan_boltzmann_law|sitefanboerzimandinglv
维恩位移定律|WEWYDL|wiens_displacement_law|weienweiyidinglv
相变|XB|phase_transition|xiangbian
物态|WT|state_of_matter|wutai
固体|GT|solid|guti
液体|YT|liquid|yeti
气态|QT|gaseous_state|qitai
熔化|RH|melting|ronghua
凝固|NG|solidification|ninggu
汽化|QH|vaporization|qihua
液化|YH|liquefaction|yehua
升华|SH|sublimation|shenghua
凝华|NH|deposition|ninghua
潜热|QR|latent_heat|qianre
熔化热|RHR|heat_of_fusion|ronghuare
汽化热|QHR|heat_of_vaporization|qihuare
饱和蒸气|BHZQ|saturated_vapor|baohezhengqi
饱和蒸气压|BHZQY|saturated_vapor_pressure|baohezhengqiya
临界温度|LJWD|critical_temperature|linjiewendu
临界压强|LJYQ|critical_pressure|linjieyaqiang
三相点|SXD|triple_point|sanxiangdian
湿度|SD|humidity|shidu
相对湿度|XDSD|relative_humidity|xiangduishidu
露点|LD|dew_point|ludian
热膨胀|RPZ|thermal_expansion|repengzhang
线膨胀|XPZ|linear_expansion|xianpengzhang
体膨胀|TPZ|volume_expansion|tipengzhang
膨胀系数|PZXS|coefficient_of_expansion|pengzhangxishu
表面张力|BMZL|surface_tension|biaomianzhangli
毛细现象|MXXX|capillary_phenomenon|maoxixianxiang
浸润|JR|wetting|jinrun
不浸润|BJR|non_wetting|bujinrun
黏滞现象|NZXX|viscous_phenomenon|nianzhixianxiang
平均自由程|PJZYC|mean_free_path|pingjunziyoucheng
方均根速率|FJGSL|root_mean_square_speed|fangjungensulv
最概然速率|ZGRSL|most_probable_speed|zuigairansulv
平均速率|PJSL|average_speed|pingjunsulv
能均分定理|NJFDL|equipartition_theorem|nengjunfendingli
自由度|ZYD|degree_of_freedom|ziyoudu
理想气体内能|LXQTNN|internal_energy_of_ideal_gas|lixiangqitineineng
气体压强公式|QTYQGS|formula_for_gas_pressure|qitiyaqianggongshi
麦克斯韦速率分布律|MKSWSLFBL|maxwell_speed_distribution|maikesiweisulvfenbulv
热力学系统|RLXXT|thermodynamic_system|relixuexitong
孤立系统|GLXT|isolated_system|gulixitong
封闭系统|FBXT|closed_system|fengbixitong
开放系统|KFXT|open_system|kaifangxitong
热库|RK|heat_reservoir|reku
""",
    "modern_physics_terms.csv": """
近代物理|JDWL|modern_physics|jindaiwuli
狭义相对论|XYXDL|special_relativity|xiayixiangduilun
相对性原理|XDXYL|principle_of_relativity|xiangduixingyuanli
光速不变原理|GSBBYL|principle_of_constancy_of_light_speed|guangsububianyuanli
洛伦兹变换|LLZBH|lorentz_transformation|luolunzibianhuan
同时的相对性|TSDXDX|relativity_of_simultaneity|tongshidexiangduixing
时间间隔|SJGG|time_interval|shijianjiange
固有时|GYS|proper_time|guyoushi
时间延缓|SJYH|time_dilation|shijianyanhuan
长度收缩|CDSS|length_contraction|changdushousuo
固有长度|GYCD|proper_length|guyouchangdu
相对论速度变换|XDLSDBH|relativistic_velocity_transformation|xiangduilunsudubianhuan
相对论动量|XDLDL|relativistic_momentum|xiangduilundongliang
相对论质量|XDLZL|relativistic_mass|xiangduilunzhiliang
静质量|JZL|rest_mass|jingzhiliang
静能|JN|rest_energy|jingneng
总能量|ZNL|total_energy|zongnengliang
质能关系|ZNGX|mass_energy_relation|zhinengguanxi
质能方程|ZNFC|mass_energy_equation|zhinengfangcheng
能量动量关系|NLDLGX|energy_momentum_relation|nengliangdongliangguanxi
相对论因子|XDLYZ|lorentz_factor|xiangduilunyinzi
闵可夫斯基时空|MKFSJSK|minkowski_spacetime|minkefusijishikong
时空间隔|SKJG|spacetime_interval|shikongjiange
四维时空|SWSK|four_dimensional_spacetime|siweishikong
光锥|GZ|light_cone|guangzhui
事件|SJ|event|shijian
世界线|SJX|worldline|shijiexian
相对论力学|XDLLX|relativistic_mechanics|xiangduilunlixue
紫外灾变|ZWZB|ultraviolet_catastrophe|ziwaizaibian
黑体辐射|HTFS|blackbody_radiation|heitifushe
能量子|NLZ|energy_quantum|nengliangzi
普朗克常量|PLKCL|planck_constant|pulangkechangliang
普朗克假设|PLKJS|planck_hypothesis|pulangkejiashuo
普朗克公式|PLKGS|planck_formula|pulangkegongshi
光电效应|GDXY|photoelectric_effect|guangdianxiaoying
光电子|GDZ|photoelectron|guangdianzi
遏止电压|EZDY|stopping_voltage|ezhidianya
截止频率|JZPL|cutoff_frequency|jiezhipinlv
逸出功|YCG|work_function|yichugong
爱因斯坦光电方程|AYSTGDFC|einstein_photoelectric_equation|aiyinsitanguangdianfangcheng
光量子|GLZ|light_quantum|guangliangzi
光子|GZ|photon|guangzi
康普顿效应|KPDXY|compton_effect|kangpudunxiaoying
康普顿散射|KPDSS|compton_scattering|kangpudunsanshe
康普顿波长|KPDBC|compton_wavelength|kangpudunbochang
物质波|WZB|matter_wave|wuzhibo
德布罗意波|DBLYB|de_broglie_wave|debuluoyibo
德布罗意波长|DBLYBC|de_broglie_wavelength|debuluoyibochang
电子|DZ|electron|dianzi
质子|ZZ|proton|zhizi
中子|ZZ|neutron|zhongzi
原子|YZ|atom|yuanzi
原子核|YZH|atomic_nucleus|yuanzihe
核式结构|HSJG|nuclear_model|heshijiegou
卢瑟福散射|LSFSS|rutherford_scattering|lusefusanshe
卢瑟福原子模型|LSFYZMX|rutherford_atomic_model|lusefuyuanzimoxing
玻尔原子模型|BEYZMX|bohr_atomic_model|boeryuanzimoxing
玻尔假设|BEJS|bohr_postulates|boerjiashuo
定态|DT|stationary_state|dingtai
能级|NJ|energy_level|nengji
基态|JT|ground_state|jitai
激发态|JFT|excited_state|jifatai
跃迁|YQ|transition|yueqian
量子数|LZS|quantum_number|liangzishu
主量子数|ZLZS|principal_quantum_number|zhuliangzishu
氢原子|QYZ|hydrogen_atom|qingyuanzi
氢光谱|QGP|hydrogen_spectrum|qingguangpu
巴耳末系|BEMX|balmer_series|baermoxi
赖曼系|LMX|lyman_series|laimanxi
帕邢系|PXX|paschen_series|paxingxi
里德伯常量|LDBCL|rydberg_constant|lidebochangliang
经典量子模型|JDLZMX|old_quantum_model|jingdianliangzimoxing
""",
}


def parse_rows(text):
    rows = []
    for raw in text.splitlines():
        raw = raw.strip()
        if not raw:
            continue
        parts = raw.split("|")
        if len(parts) != 4:
            raise ValueError(f"Bad row: {raw!r}")
        cn, initials, english, pinyin = parts
        initials = initials.strip().upper()
        english = english.strip()
        pinyin = pinyin.strip().replace(" ", "").lower()
        rows.append([cn.strip(), initials, english, pinyin])
    return rows


def write_table(path, rows):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with Path(path).open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, lineterminator="\n")
        writer.writerow(HEADER)
        for i, (cn, initials, english, pinyin) in enumerate(rows, 1):
            writer.writerow([
                i,
                cn,
                initials,
                len(initials),
                english,
                len(english),
                pinyin,
                len(pinyin),
            ])


def main():
    for filename, text in TABLES.items():
        rows = parse_rows(text)
        path = PHYSICS_SIMPLE_DIR / filename
        write_table(path, rows)
        print(f"{path.relative_to(ROOT)}: {len(rows)} rows")


if __name__ == "__main__":
    main()
